version: "3.7"
services:
    db:
        image: postgres:15
        container_name: db_app
        command: -p 5435
        expose:
            - 5435
        env_file:
            - /src/.env
    app:
        build:
            context: .
        env_file:
            - /src/.env
        container_name: app
        restart: on-failure:20
        environment:
            - APP_MODE=prod
        command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 80"
        ports:
            - 9999:80
        depends_on:
            - db
        
            